TeamATM/toonchat-client

- src/components/chat/CharacterSpeak.tsx
- src/components/chat/Footer.tsx
- src/components/chat/Main.tsx
- src/components/chat/MySpeak.tsx
- src/components/chat/TimeStamp.tsx
- src/pages/chat/leeyj.tsx
> Feature : 채팅마다 timestamp 생성

- src/components/chat/TimeStamp.tsx
- 오후 2시 6분이 '2:6 PM'으로 나오는 것을 '2:06 PM'으로 수정
- hour 부분은 02시보다 2시가 더 예뻐보여서 그대로 둠
> 🐝 Fix: 0시 00분 양식으로 수정

- src/components/chat/CharacterSpeak.tsx
- src/components/chat/Footer.tsx
- src/components/chat/Main.tsx
- src/components/chat/MySpeak.tsx
- src/pages/api/hello.ts
- 채팅 입력부분에서 고민이 생겨서 이슈를 남겼음 (#10)
- 채팅이 길어지면 옆으로 커지는 경우가 있었는데 이런 현상을 CSS 조정으로 풀어냄
- 채팅 컴포넌트들의 CSS를 각각의 변수로 넣는 리팩토링 진행
- 채팅이 입력되면 당연스럽게도 스크롤은 맨 아래로 내려가야하기 때문에 기능 추가 해놓음
> Feature: 긴 내용의 채팅은 줄바꾸고 채팅이 많아지면 스크롤 다운

- src/pages/user/login.tsx
- src/pages/user/signup.tsx
이전에 로그인 페이지를 구성할 때 고민했던 컴포넌트의 재사용성을 확인할 수 있었습니다.
UI만 구성하는 것은 컴포넌트만 끌어서 넣고 텍스트만 바꾸면 되는 수준이라서 20분도 걸리지 않았습니다.
코드를 작성하면서 UI는 이런 컴포넌트 방식을 채택하는 것으로 가닥을 잡을 생각입니다.
이젠 util 디렉토리를 따로 만들어서 submit이나 api 처리 등의 함수를 따로 분류하고자 합니다.
그 이유는
테스트 코드를 작성하고 확인하는 과정에서도 UI는 바뀔 수 있어도 기능은 바뀌지 않을 것이기에 정말 유리할 것이고
컴포넌트는 컴포넌트일 뿐, API를 호출하고 받는 과정을 하는 것은 다른 레이어에서 해주는 것이 관리하기 수월할 것이기 때문입니다.
> Feature: 회원가입 페이지 UI 구성

- src/components/user/Input.tsx
- src/components/user/PasswordInput.tsx
- src/pages/api/users.ts
- src/pages/api/users/login.ts
- src/pages/user/login.tsx
- src/pages/user/signup.tsx
기존에 Input 태그로 만들어진 form을 api로 보내는 방식으로 구현했습니다.
API 호출 과정에서 현재에는 내장된 함수인 fetch를 사용했으나 axios로 바뀌어야할 것 같습니다.
우리의 채팅 응답이 바로바로 안올수 있는데,
응답이 늦어서 응답 실패가 되어버릴 수 있기 때문에 응답 시간을 조정이 편한 툴이 axios이기 때문에 사용하고자 합니다.
(그 밖에도 보안적으로도 좋고, 코드도 json  변환과정을 따로 안해도 되기 때문에 가독성 면에서도 좋습니다.)
> Feature: 로그인, 회원가입이 기능하도록 구현 (임시 API를 활용)

- .gitignore
- next.config.js
- package.json
- src/components/chat/Header.tsx
- src/components/chat/MessageInput.tsx
- src/pages/api/chat/[character_id].tsx
- src/store/chat.ts
- src/store/socket.ts
- yarn.lock
채팅방 안에서만 쓰지 않고 사이트 전체에서 사용 가능하게 하기 위해
zustand를 사용하였음(맞나?)
> Feature: STOMP를 이용한 채팅

- src/components/main/Friends.tsx
- src/components/main/SearchBar.tsx
- src/components/main/friend/Friend.tsx
- src/components/main/friend/FriendHashTag.tsx
- src/components/main/friend/FriendInfo.tsx
- src/components/main/friend/FriendWrapper.tsx
- src/components/main/recommend/RecommendBox.tsx
- src/components/toast/Toast.tsx
- src/pages/user/index.tsx
- src/styles/color.tsx
- 스크롤바 때문에 배경 margin이 틀어지는 것을 확인했고, 스크롤바를 안보이도록 설정
- 친구, 추천친구 hover시 색 변경
- Toast 컴포넌트 생성 : 검색기능을 사용시 뜨도록 조치함 (이후에도 자주 사용될 UI인듯 함)
- 채팅 내역에서도 사용할 부분이 있어서 컴포넌트 재사용이 가능하도록 분리
> Refactor: 친구목록 페이지 리팩토링

- src/components/main/ChatLogs.tsx
- src/components/main/friend/ChatBadge.tsx
- src/pages/chat/index.tsx
- src/pages/user/index.tsx
- 기존에 만들어놓은 컴포넌트들을 대부분 활용했기 때문에 UI 구성은 어렵지 않았습니다.
- API가 완성된다면 이제 뭐 채팅 관련 UI는 거의 다 되부럿다고 봐도 됩니다.
> Feature: 이전 채팅 내역 페이지 UI 구현

- src/components/bottomNavigation/BottomNavigation.tsx
- src/pages/community/index.tsx
- src/pages/index.tsx
- src/pages/profile/index.tsx
- 라우팅을 해야하기 때문에 최소한 페이지가 존재해야합니다. 최소한의 꾸밈(?)으로 이 3가지 페이지를 구현했습니다.
> Feature: 랜딩, 커뮤니티, 프로필 페이지 껍데기 구현

- src/store/socket.ts
> 🐝 Fix: 서버측 채팅 메시지 양식에 맞춰서 포맷 변경

- .gitignore
- src/components/bottomNavigation/BottomNavigation.tsx
- src/components/chat/characterHeader/CharacterInfo.tsx
- src/components/chat/characterHeader/FriendShip.tsx
- src/components/dialog/Dialog.tsx
- src/components/main/SearchBar.tsx
- src/components/main/SectionLine.tsx
- src/components/main/SectionTitle.tsx
- src/components/main/friend/FriendHashTag.tsx
- src/components/main/friend/FriendWrapper.tsx
- src/components/main/recommend/RecommendBox.tsx
- src/components/toast/Toast.tsx
- src/components/user/DivideLine.tsx
- src/components/user/DivideLineText.tsx
- src/components/user/Input.tsx
- src/components/user/PasswordInput.tsx
- src/components/user/ToForgetPassword.tsx
- src/components/user/socialLoginButton/AppleButton.tsx
- src/components/user/socialLoginButton/GoogleButton.tsx
- src/components/user/socialLoginButton/NaverButton.tsx
- src/pages/_app.tsx
- src/pages/chats/[character].tsx
- src/pages/community/index.tsx
- src/pages/index.tsx
- src/pages/login/index.tsx
- src/pages/profile/index.tsx
- src/pages/signup/index.tsx
- URL 링크가 잘못된 것을 파악하고 수정 하면서 테스트코드의 중요성을 많이 느낍니다.
> Fix: 추천친구를 눌렀을 때 연결되는 url 링크 수정, ESLint에 맞게 코드 수정

- .github/ISSUE_TEMPLATE/documentation.md
- .github/ISSUE_TEMPLATE/question.md
- .github/workflows/playwright.yml
- .gitignore
- e2e/example.spec.ts
- e2e/landing.spec.ts
- jest.config.mjs
- package.json
- playwright.config.ts
- yarn.lock
- 기존에 url 패턴이 바뀐다거나, 컴포넌트 사용방식이 바뀌었을 때 미처 찾지 못해서 이후에 Fix 해야하는 경우가 있었습니다.
- jest만으론 완전히 찾기 어렵기 때문에 유저 시나리오대로 따라갈 수 있는 E2E 테스트를 사용하고자 하고, 가장 대중적인 툴 중 하나인 playwright를 채택했습니다.
- 모든 유저 시나리오대로 하기엔 아직 깊이가 부족하기에 랜딩페이지에서 유저가 로그인 버튼, 영준과의 대화 버튼을 누른다라는 시나리오만을 확인했습니다.
- [Play Wrighr 공식 문서](https://playwright.dev/)
- Jest 테스트 러너와 Playwright Test 사이에 발생하는 충돌이 개발 과정 중간에 있어서 jest의 config 파일에 e2e 테스트 코드가 있는 디렉토리는 무시하도록 하는 설정을 추가했습니다.
> Test: E2E test 적용

- src/utils/api/chats.ts
- src/utils/axiosInstance/defaultInstance.ts
- Axios 인스턴스에 BASE URL을 설정했음에도 적용이 안되는 부분은 '/'의 유무로 밝혀짐
- 그 밖에도 에러 핸들링을 미들웨어를 통해서 가능하다는 것을 알고 초안으로 적용
- BASE_URL 적용
- 에러 핸들링 적용
- Amplify를 적용한 것을 빌드되는 지 확인
> Reafactor: axios instance 설정

- next.config.js
- src/store/socket.ts
- src/utils/axiosInstance/defaultInstance.ts
- amplify 환경에서 확인하기 위해서 NEXT_PUBLIC이라는 단어가 접두로 필요한 것을 확인함
> 🐝 Fix: env 파일의 변수명 변경

- src/pages/profile/index.tsx
- build 에러를 확인하기 위해서 타입을 any로 지정...
- 제발...
> 🐝 Fix: build 에러를 확인하기 위해서 타입을 any로 지정

- src/pages/api/auth/[...nextauth].ts
- https://github.com/nextauthjs/next-auth/issues/591
- 살려줘
- https://github.com/nextauthjs/next-auth/issues/591
- 살려줘
- 이번에도 안되면 어떻게 해야할지 모르겠지만 PR 남발은 못할 것 같음...
> Fix: amplify로 배포시 생기는 이슈

- src/pages/api/auth/[...nextauth].ts
- src/utils/axiosInstance/clientServerInstance.ts
- URL 문제인 것일 수 있어서 진짜 찐 마지막으로 merge
- Develop이 되기 전에 미리 확인할 수 있는 환경 조성을 해봐야겠다고 느낌
- 배포가 안된 상태로 확인하려니까 어려움을 많이 느꼈음
- 이제 안되면 내려놓고 다른 것 할 예정
> Fix: 로그인에 필요한 URL 수정

- src/components/common/head/GA.tsx
- src/pages/_app.tsx
- Google Analytics를 주입하여 지표를 확인하기!
- close #69 
- GA ID를 발급받아서 적용했습니다.
> Feat: GA tag 주입

- src/pages/api/auth/[...nextauth].ts
- src/pages/signup/index.tsx
- src/utils/api/clientServer.ts
- src/utils/axiosInstance/clientServerInstance.ts
- src/utils/axiosInstance/defaultInstance.ts
- 백엔드에서 만들어진 로그인 API를 연결했습니다.
- close #70 
- 기존 땜빵해놨던 next 자체 로그인 기능에서 백엔드로 연결하도록 설정했습니다.
- 아직 서버측 dev에만 적용되어있는 것이 특징입니다.
- 아직 소셜로그인은 되지 않았습니다.
- 로그인, 회원가입 기능이 로컬에서 잘 작동하는 것을 확인했습니다.
> Feature: Credential Login 구현

- next.config.js
- src/pages/api/auth/[...nextauth].ts
> Hot fix: 로그인 할 때 redirect url을 확인

- src/pages/api/auth/[...nextauth].ts
- src/pages/api/users/signup.ts
- src/pages/signup/index.tsx
- src/utils/api/accounts.ts
- src/utils/axiosInstance/clientInstance.ts
- Signup API 연결
- 클라이언트에서 회원가입시 NEXT의 API로 연결되고 NEXT의 API를 통해 spring 서버 측으로 회원가입 API를 넘겨주는 방식
- 기대효과 : 회원가입은 넥스트 서버를 통하지 않으면 할 수 없게 됨
- 로컬에선 회원가입이 너무 잘됩니다. 배포만 잘 되면 좋을 듯
> Feature: signup API 연결

- next.config.js
- src/pages/api/auth/[...nextauth].ts
- src/pages/api/users/signup.ts
- 살려줘
- CORS가 가장 어려운 것 같습니다
- OPTION에 대해서 배웠습니다.
- CORS를 해결하기 위해 OPTION 요청 허용
- next config에 환경변수 추가
- CORS 오류 메시지에 따라, API 핸들러를 업데이트
- 웹 브라우저가 실제 HTTP 요청을 보내기 전에 서버로 보내는 OPTION 요청을 CORS 헤더와 함께 응답
- Access-Control-Allow-Methods 헤더에 OPTIONS를 추가하여 OPTIONS 요청 허용
> Hot-Fix: cors 오류를 수정

- next.config.js
- src/pages/api/auth/[...nextauth].ts
- 배포 버전에서는 시크릿키와 쿠키 설정이 필요하다하여 설정
> Feature: next-auth 시크릿키 설정 & cookie 설정

- src/components/chat/Header.tsx
- src/store/socket.ts
- src/utils/axiosInstance/chatInstance.ts
- src/utils/axiosInstance/clientInstance.ts
- src/utils/axiosInstance/defaultInstance.ts
- types/next-auth.d.ts
- 로그인이 되기 때문에 개인의 토큰을 사용할 수 있도록 했습니다.
- closed #81 
- 채팅서버와 API 연결로 history에 토큰을 활용할 수 있게 됐습니다.
- 채팅서버와 소켓 통신에 토큰을 활용할 수 있게 됐습니다.
> Feature: Chat 서버와 토큰 연결

- src/pages/api/auth/[...nextauth].ts
- types/next-auth.d.ts
- 토큰 타입이 맞지 않아서 build가 되지 않았음
- 선언부, next-auth 내의 session 타입 수정 (추후에 타입 리팩토링때 전체적으로 해결해야할 듯 함)
> Fix: token type 수정

- src/components/chat/MessageInput.tsx
- src/pages/chats/[character].tsx
- src/store/socket.ts
- 캐릭터 id의 타입을 string -> int 변경
- (해결하고자 하는 이슈의 이름과 해시태그 번호를 적어주세요. 예: `이슈명 #123`)
- 캐릭터 id의 타입을 string -> int 변경
- 기존 레거시 코드가 꽤가 있어 일부만 변경하였음.
- 로컬에서 채팅서버에 채팅 하였을 때 정상 동작.
> Fix: change type of characterId from string to number

- package.json
- src/pages/_app.tsx
- yarn.lock
- 동우멘토님의 조언으로 데이타독이라는 신기술로 저희는 모니터링을 해봅니다.
- 백엔드에도 적용하겠지만 프론트에도 유저 모니터링을 시작했습니다.
- 이제 데이터독을 잘 활용해보아요.
- 아주 귀엽게 연결되었습니다.
> Feature: DataDog으로 모니터링을 시작합니다.

- src/components/common/skeleton/RecommendBoxSkeleton.tsx
- src/components/common/skeleton/SkeletonList.tsx
- src/components/community/BoardList.tsx
- src/components/friends/ChatLogs.tsx
- src/components/friends/Friends.tsx
- src/components/friends/Recommends.tsx
- src/components/friends/friend/ChatBadge.tsx
- src/components/friends/friend/FriendSkeleton.tsx
- src/pages/chats/index.tsx
- src/styles/GlobalStyles.tsx
- 사용자의 사용자 경험을 위해 스켈레톤 UI를 적용했습니다.
- 게시판 목록, 친구 목록, 채팅 목록에 스켈레톤 UI를 적용합니다.
- 스켈레톤 UI에 필요한 CSS 부분은 변수화하여 따로 리팩토링을 했습니다.
- 아직 게시판이나 게시글, 채팅방에는 적용되지 않았습니다.
> Feature: 스켈레톤 UI 적용

- src/components/account/socialLoginButton/GoogleButton.tsx
- src/components/account/socialLoginButton/KakaoButton.tsx
- src/components/account/socialLoginButton/NaverButton.tsx
- src/pages/api/auth/[...nextauth].ts
> Feature: Social Login 세팅

- src/utils/api/accounts.ts
- src/utils/api/character.ts
- src/utils/axiosInstance/ssrInstance.ts
> Fix: 소셜로그인 URL 패턴 수정
